export const alum_names = [
  "Yalda Azari",
  "Amirmasood Shojaee",
  "Sarina Badre Rajaei",
  "Seiedarshia Zarifian Kamyab",
  "Shina Namakian",
  "Arnica Kiani",
  "Farbod Azaripour Masooleh",
  "Sara Nazemi",
  "Arash Ghafoori",
  "Sahel Nazemi",
  "Elmira Noohpisheh",
  "Aida Beigi",
  "Sara Ghasemi",
  "Armin Sariaslani ",
  "Asal Ozlati",
  "Bardia Rahmati",
  "Ayda Beigloo",
  "Hediyeh Zohourian",
  "Pardis Ghanaeian",
  "Sepehr Bozorgi",
  "Lida Nosrati",
  "Mohammadsam Shahryari",
  "Hidika Khoshnoud",
  "Fatemeh Zahiri",
  "Maryam Vaseghi-Shanjani",
  "Maral Aminaei",
  "Helia Hashemi",
  "Erfan Jamalifar",
  "Kiarash Forootan",
  "Parichehr Yazdanshenas",
  "Anahita Abtahi",
  "Aryana Zarandi",
  "Sara Rafiei",
  "Yasi Averdi",
  "Farzad Vakili",
  "Amirreza Taghiabadi",
  "Parnia Abolghasemi",
  "Mohammad Farzbod",
  "Danial Aminaei",
  "Hamid Ghasemi",
];
